# Generated by Django 5.1.3 on 2025-01-10 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ['-score', 'completed_at']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option1',
            new_name='option_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2',
            new_name='option_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option3',
            new_name='option_c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option4',
            new_name='option_d',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together={('quiz', 'user')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='quizzes.quiz'),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='attempt_date',
        ),
    ]
