# Generated by Django 5.1.3 on 2025-01-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
